<?php

/**
 * @file
 * Contains opcache.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opcache_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opcache module.
    case 'help.page.opcache':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows Drupal to administer PHP OPcache.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opcache_theme() {
  $theme = [];

  return $theme;
}
